local APP_NAME = "pocket_remote_v2"
local APP_PATH = "/pocket_remote_v2.lua"
local APP_URL = "https://raw.githubusercontent.com/NekoSuneProjects/CCTweaks-Scripts-Lua/main/Jukebox/pocket_remote_v2.lua"
local STARTUP_PATH = "/startup.lua"
local BACKUP_PATH = "/startup_pocket_remote_backup.lua"

local function readFile(path)
    if not fs.exists(path) then
        return nil
    end

    local handle = fs.open(path, "r")
    if not handle then
        return nil
    end

    local data = handle.readAll()
    handle.close()
    return data
end

local function writeFile(path, data)
    local handle = fs.open(path, "w")
    if not handle then
        error("Failed to write " .. path)
    end

    handle.write(data)
    handle.close()
end

local function download(url)
    if not http then
        error("HTTP API is disabled")
    end

    local handle, err = http.get(url, nil, true)
    if not handle then
        error("Download failed: " .. tostring(err))
    end

    local data = handle.readAll()
    handle.close()
    return data
end

local function buildStartup()
    return string.format([=[-- Auto-generated by install_pocket_remote.lua
local APP_NAME = %s
local APP_PATH = %s
local APP_URL = %s
local SKIP_DELAY = 3

local function readFile(path)
    if not fs.exists(path) then
        return nil
    end

    local handle = fs.open(path, "r")
    if not handle then
        return nil
    end

    local data = handle.readAll()
    handle.close()
    return data
end

local function writeFile(path, data)
    local handle = fs.open(path, "w")
    if not handle then
        error("Failed to write " .. path)
    end

    handle.write(data)
    handle.close()
end

local function download(url)
    if not http then
        error("HTTP API is disabled")
    end

    local handle, err = http.get(url, nil, true)
    if not handle then
        error("Download failed: " .. tostring(err))
    end

    local data = handle.readAll()
    handle.close()
    return data
end

local function updateApp()
    local remote = download(APP_URL)
    local localData = readFile(APP_PATH)

    if localData ~= remote then
        writeFile(APP_PATH, remote)
        print("Updated " .. APP_NAME)
    else
        print(APP_NAME .. " is current")
    end
end

local function waitForSkip()
    term.setBackgroundColor(colors.black)
    term.setTextColor(colors.white)
    term.clear()
    term.setCursorPos(1, 1)
    print("Booting " .. APP_NAME)
    print("Checking for updates...")
    print("")
    print("Press any key within " .. SKIP_DELAY .. "s to skip auto-start.")

    local timer = os.startTimer(SKIP_DELAY)

    while true do
        local event = {os.pullEvent()}
        if event[1] == "timer" and event[2] == timer then
            return false
        elseif event[1] == "key" or event[1] == "char" or event[1] == "mouse_click" then
            return true
        end
    end
end

local function runApp()
    term.setBackgroundColor(colors.black)
    term.setTextColor(colors.white)
    term.clear()
    term.setCursorPos(1, 1)
    print("Starting " .. APP_NAME .. "...")
    print("Use Q or Backspace in-app to exit.")
    sleep(0.5)

    local ok, result = pcall(shell.run, APP_PATH)
    if not ok then
        print("App crashed: " .. tostring(result))
        return
    end

    if result == false then
        print("App exited with an error.")
    else
        print("App closed.")
    end
end

if waitForSkip() then
    term.setBackgroundColor(colors.black)
    term.setTextColor(colors.white)
    term.clear()
    term.setCursorPos(1, 1)
    print("Auto-start skipped.")
    return
end

local ok, err = pcall(updateApp)
if not ok then
    print("Update check failed: " .. tostring(err))
end

if not fs.exists(APP_PATH) then
    error("Missing app file: " .. APP_PATH)
end

runApp()
]=], textutils.serialize(APP_NAME), textutils.serialize(APP_PATH), textutils.serialize(APP_URL))
end

local function installStartup()
    local startup = buildStartup()
    local current = readFile(STARTUP_PATH)

    if current and current ~= startup and not fs.exists(BACKUP_PATH) then
        writeFile(BACKUP_PATH, current)
    end

    writeFile(STARTUP_PATH, startup)
end

local function installApp()
    local app = download(APP_URL)
    writeFile(APP_PATH, app)
end

term.setBackgroundColor(colors.black)
term.setTextColor(colors.white)
term.clear()
term.setCursorPos(1, 1)

print("Installing " .. APP_NAME .. "...")
installStartup()
installApp()
print("Installed startup updater to " .. STARTUP_PATH)
print("Launching " .. APP_NAME .. "...")
sleep(0.5)
shell.run(APP_PATH)
